name: future_server
version: 1.1.1+1
description: future_server is package based on several packages make a new gate to back-end development using dart .. it's a new opputunity to build back-end with dart just with future_server.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  get_server: ^1.1.1
  #firedart: 0.9.0+1
  galileo_mysql: ^3.0.0

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.16.0

repository: https://github.com/Kar1mMohamed/future_server

dart:
  package: