name: future_server
version: 1.2.1+2
description: future_server is package based on several packages make a new gate to back-end development using dart .. it's a new opputunity to build back-end with dart just with future_server.
repository: https://github.com/Kar1mMohamed/future_server
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  get_server: ^1.2.1
  galileo_mysql: ^3.0.0
  hive: ^2.2.3

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.16.0

dart: 
  package: null

